name: e2e
"on":
  pull_request: null
  push:
    branches:
    - '**'
  schedule:
  - cron: 0 10 * * SAT
permissions:
  contents: read
jobs:
  kind:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Setup Kubernetes
      uses: helm/kind-action@v1.5.0
      with:
        version: v0.17.0
        cluster_name: kind
    - name: Setup Go
      uses: actions/setup-go@v3
    - name: Build k8suser binary
      uses: goreleaser/goreleaser-action@v4
      with:
        distribution: goreleaser
        version: latest
        args: release --snapshot --skip-publish --rm-dist
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Run integration tests
      run: |
        ./test/test.sh
    - name: Debug failure
      if: failure()
      run: |
        kubectl logs || true
